### ISSUE TITLE
[Question] the div of color editor is always in the editor

### ISSUE THREAD

**Issue by Azakur4** [thomaslindstrom/color-picker#101]
i want to know why u decide always maintain the color editor in atom?

i like a lot ur package (congrats) but i have doubt, i don't work all the time in styles files or working with colors maybe other people do, i only want to know that is good to have this always loaded in the html of the atom editor or we can remove and add when u call the color picker.

**Comment by thomaslindstrom** [comment]
Hi, @Azakur4! Keeping the Color Picker in the `DOM`, yet invisible, clears off most of the performance concerns one might have. Adding the, complex, Color Picker element on demand, on the other hand, would result in a sluggish experience for the users. It remains completely idle when not used, so it's not doing anything I would consider bad for performance. Thanks!
