### ISSUE TITLE
Uncaught SyntaxError: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('hsl(NaN, 100%, 50%)') could not be parsed as a color.

### ISSUE THREAD

**Issue by nazarioa** [thomaslindstrom/color-picker#102]
[Enter steps to reproduce below:]

created a new CSS element
.tags li{
display: inline;
font-family: sans-serif;
color: ...
At the ... above i hit the short cut keys for color and I got the exception.

**Atom Version**: 0.202.0
**System**: Mac OS X 10.10.3
**Thrown From**: [color-picker](https://github.com/thomaslindstrom/color-picker) package, v2.0.2

### Stack Trace

Uncaught SyntaxError: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('hsl(NaN, 100%, 50%)') could not be parsed as a color.

```
At /Users/nazario/.atom/packages/color-picker/lib/extensions/Saturation.coffee:108

Error: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('hsl(NaN, 100%, 50%)') could not be parsed as a color.
  at Error (native)
  at Object._this.canvas.render (/Users/nazario/.atom/packages/color-picker/lib/extensions/Saturation.coffee:108:35)
  at /Users/nazario/.atom/packages/color-picker/lib/extensions/Saturation.coffee:124:29
  at Object.emit (/Users/nazario/.atom/packages/color-picker/lib/modules/Emitter.coffee:11:23)
  at Object.emitColorChanged (/Users/nazario/.atom/packages/color-picker/lib/extensions/Hue.coffee:32:22)
  at /Users/nazario/.atom/packages/color-picker/lib/extensions/Hue.coffee:172:47
  at Object.emit (/Users/nazario/.atom/packages/color-picker/lib/modules/Emitter.coffee:11:23)
  at Object.emitSelectionChanged (/Users/nazario/.atom/packages/color-picker/lib/extensions/Hue.coffee:26:22)
  at Object._this.control.setSelection (/Users/nazario/.atom/packages/color-picker/lib/extensions/Hue.coffee:161:36)
  at /Users/nazario/.atom/packages/color-picker/lib/extensions/Hue.coffee:169:30
  at Object.emit (/Users/nazario/.atom/packages/color-picker/lib/modules/Emitter.coffee:11:23)
  at Object.emitInputColor (/Users/nazario/.atom/packages/color-picker/lib/ColorPicker-view.coffee:227:26)
  at Object.open (/Users/nazario/.atom/packages/color-picker/lib/ColorPicker-view.coffee:376:18)
  at atom-text-editor.<anonymous> (/Users/nazario/.atom/packages/color-picker/lib/ColorPicker.coffee:42:68)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:521:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
     -1:19.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:18.2.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:33.7.0 editor:newline (atom-text-editor.editor.is-focused)
  8x -0:30.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:25.5.0 editor:newline (atom-text-editor.editor.is-focused)
  4x -0:23 core:backspace (atom-text-editor.editor.is-focused)
     -0:18.6.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:17.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:16.4.0 editor:newline (atom-text-editor.editor.is-focused)
  5x -0:10.6.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:09.6.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:09.5.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -0:07.8.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:06.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:05.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:02.4.0 color-picker:open (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "atom-terminal-panel"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.2
linter, v0.12.6
minimap, v4.9.0
minimap-bookmarks, v0.1.0
minimap-color-highlight, v4.1.4
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.3
minimap-highlight-selected, v4.3.0
minimap-selection, v4.2.0
script, v2.23.0

# Dev
No dev packages
```

**Comment by Tribex** [comment]
What was the text you were selecting/editing?

**Comment by thomaslindstrom** [comment]
Hi, @nazarioa. I can't seem to reproduce this. Do you have a more complete code example? Opening the color picker at `...` doesn't produce the error here.

**Comment by xiaohenry** [comment]
I also am having a similar problem.
Uncaught SyntaxError: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('rgba(-Infinity, NaN, Infinity, 1)') could not be parsed as a color.

**Comment by thomaslindstrom** [comment]
Hi, @xiaohenry. Do you have any information regarding the circumstances that triggered this error?

**Comment by xiaohenry** [comment]
@thomaslindstrom this started happening after the most recent update. I'm not sure if it came with the Atom update to 0.202 or webbox update. This happens whenever I use the command CMD+SHIFT+C on any file

**Comment by thomaslindstrom** [comment]
@xiaohenry Weird. Have you set any settings in `color-picker`, or are they the default values? I.e. did you set your preferred color format and such?

**Comment by xiaohenry** [comment]
@thomaslindstrom I have not. I tried reinstalls, etc, but still getting issues. Sorry if I am not being too helpful, I'll try to personally look more into it in a little bit when I get some time

**Comment by thomaslindstrom** [comment]
Don't worry, @xiaohenry, you're being helpful! It's just I have no idea where to start tracking down this bug. Could you try going into `color-picker` settings and switch off this option right here? Please try reloading after having set *“Serve a random color on open”* to `off`. 

![screen shot 2015-05-29 at 00 21 10](https://cloud.githubusercontent.com/assets/2833514/7872471/a15a965c-0598-11e5-8426-06922f56d043.png)

**Comment by xiaohenry** [comment]
Just did it. The main problem seems to be "TypeError: Cannot read property 'querySelector' of null"

**Comment by thomaslindstrom** [comment]
So the initial error message disappeared when you turned off *“Serve a random color on open”*? If you open the developer console using `CMD+ALT+I`, and enter this:
```
atom.views.getView(atom.workspace.getActiveTextEditor()).shadowRoot.querySelector
```

What is returned?

**Comment by thomaslindstrom** [comment]
Also, Atom `0.204.0` was just released, could you try updating and see if the issue is still present?

**Comment by xiaohenry** [comment]
Yes so with "Serve random color on open" ON: I get the error: Uncaught SyntaxError: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('hsl(NaN, 100%, 50%)') could not be parsed as a color.

With it OFF: Uncaught TypeError: Cannot read property 'querySelector' of null

atom.views.getView(atom.workspace.getActiveTextEditor()).shadowRoot.querySelector returns "null" initially" then "undefined" after running it multiple times. Yes I will

**Comment by thomaslindstrom** [comment]
Hi, @xiaohenry! I just pushed `color-picker` `v2.0.6`. It fixes an issue where I assumed the Shadow DOM was always activated, which is false. It's possible to deactivate it in the Atom Settings.

If you have time, would you try replicating this bug?

**Comment by xiaohenry** [comment]
Awesome that seemed to fix the problem! Great job on staying to persistent. Cheers.

**Comment by thomaslindstrom** [comment]
Amazing, thanks! Did this fix the other issue, too?
```
Uncaught SyntaxError: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('hsl(NaN, 100%, 50%)') could not be parsed as a color.
```

**Comment by xiaohenry** [comment]
@thomaslindstrom yep! Just tried turning off/on the random color generator and both work,

**Comment by thomaslindstrom** [comment]
Ohh, thank you! That's a relief. I'm glad I fixed this. I hope you enjoy being able to use the `color-picker`, now :)
