### ISSUE TITLE
README.md: Add pointer to an as-you-type CSS reloader

### ISSUE THREAD

**Issue by walles** [thomaslindstrom/color-picker#104]
Quote from README.md:

"
Automatically Replace Color: Replace selected color automatically on change. Works well with as-you-type CSS reloaders.
"

If you could add a pointer towards an as-you-type CSS reloader for Atom to that statement that would be awesome!

**Comment by thomaslindstrom** [comment]
Hi, and thanks for the suggestion! After giving this some thought, I came to the conclusion that the `color-picker` should stay unbiased. If you'd like to know where you find one, I'd do a search for `CSS live update` ;)
