### ISSUE TITLE
Show numeric values too

### ISSUE THREAD

**Issue by larsenwork** [thomaslindstrom/color-picker#107]
![screen shot 2015-05-30 at 18 17 22 copy](https://cloud.githubusercontent.com/assets/3859425/7898201/c2c02daa-06f8-11e5-8b4d-dea73adfbad8.png)
And one input field with alpha too.

Would allow for more fine grained control.

The picture is just a screenshot of the color picker in old photoshop

**Comment by thomaslindstrom** [comment]
Hi, and thanks for the suggestion. Sadly, I don't feel like this fits with the aesthetic and idea behind the `color-picker`. If you would like to use an existing color value (eg. from a designer) you could just plop it into the Atom editor.

**Comment by larsenwork** [comment]
I am a designer myself and as many other designers I find myself designing and tweaking more and more directly in the code. 

Those adjustments are often very small but getting e.g. 1degree hue color accuracy when adjusting is difficult with a slider. 

Another solution could be to show the delta change as a tooltip when dragging.

**Comment by thomaslindstrom** [comment]
I get that. However, colors, to me, are how they look – not the code value. Hence the design of the `color-picker` and the exclusion of direct code value tuning. If you would like to directly tune the code value, convert the color to a format of your liking, and do it directly in the editor. `HSL` and `HSV`, in particular, are great for doing just that.

**Comment by larsenwork** [comment]
I know - I only use HSL but I often find myself working on projects where people use e.g. hex :hurtrealbad:

**Comment by thomaslindstrom** [comment]
Convert it all to `HSL`! Jokes aside, I'll definitely think about ways to improve the precision of `color-picker`.

**Comment by larsenwork** [comment]
Hehe...I would if I could ;) 

I think tooltips when dragging would be a nice touch - could always be an option in settings. 

You could also "go big or go home" - obviously as a settings option.

![screen shot 2015-05-31 at 00 24 50](https://cloud.githubusercontent.com/assets/3859425/7899730/ffc16fca-072f-11e5-8ddd-5bb22ac65a1b.png)
