### ISSUE TITLE
Uncaught Error: Cannot find module './modules/ColorRegexes'

### ISSUE THREAD

**Issue by Zaireca** [thomaslindstrom/color-picker#110]
![screen shot 2015-06-03 at 12 25 18](https://cloud.githubusercontent.com/assets/7951182/7958884/a38867ae-09eb-11e5-9af2-e091de5b36bb.png)

**Comment by thomaslindstrom** [comment]
Hi, please update to `v2.0.3` and this error goes away.

**Comment by Zaireca** [comment]
Thanks for responding so fast. According to Atom I'm using the v2.0.3, I've just tried uninstalling and reinstalling but the same problem occurs

**Comment by Zaireca** [comment]
Sorry, I've got it working now. Thanks for your brief time.

**Comment by thomaslindstrom** [comment]
Sorry, I meant `v2.0.4`! I'm glad it works. Thanks!
