### ISSUE TITLE
Opacity value 1.0 does not work for rgba

### ISSUE THREAD

**Issue by tormodhau** [thomaslindstrom/color-picker#111]
Reading rgba with opacity 1.0 values does not work.

    @green: rgba(60, 194, 121, 1.0); //doesn't work
    @green: rgba(60, 194, 121, 1); // works    
    @green: rgba(60, 194, 121, 0.9); // works

**Comment by thomaslindstrom** [comment]
Hi! Yeah, `1.0` doesn't work. It's valid in CSS, so this is just something I forgot to implement.

**Comment by thomaslindstrom** [comment]
There's a fix for this in `v2.0.6`!
