### ISSUE TITLE
Listening "enter" press when picking a color

### ISSUE THREAD

**Issue by chiefGui** [thomaslindstrom/color-picker#113]
Yo!

I love your plug-in—it excluded the need of opening Photoshop for picking colors, thank you very much for it!

By the bye, the matter here is _slightly_ serious: every time I select a color then press `enter`, it closes the popup without pasting the hex/rgba/etc of the selected color.

Is this a bug? A non-thought feature?

Thanks.

**Comment by thomaslindstrom** [comment]
Thanks! I recently rewrote the entire `color-picker` source. Replacing or pasting current color on `enter` used to be a feature, but I seem to have forgotten to include it. Expect a patch in a few minutes!

**Comment by thomaslindstrom** [comment]
Thanks again, @chiefGui, this is now included in `v2.0.5`.

**Comment by chiefGui** [comment]
Thank you very much, man! :+1:
