### ISSUE TITLE
Split view is buggy...

### ISSUE THREAD

**Issue by JamenMarz** [thomaslindstrom/color-picker#117]
Split view works, but it's buggy and annoying sometimes...

For instance, if I do a top and bottom split, then try to use the color picker on the bottom pane, this is what happens:

(Cursor position outlined in red...)
![Top and bottom split view bug](https://cloud.githubusercontent.com/assets/6251703/8267459/240f9032-1720-11e5-9910-2b7286147f16.png)

This bug also seems apparent when doing it in a left and right split view:

![Left and right split view bug](https://cloud.githubusercontent.com/assets/6251703/8267470/b67fed72-1720-11e5-874f-a2c1304f8154.png)

Although it does put the color code in the correct place, it's quite annoying when trying to control the box...  I think this is just simply a positioning error.

I'm not sure if this is limited to Linux (the OS I use) or other OS's too, because I saw the issue #1.

**Comment by thomaslindstrom** [comment]
Hi, and thanks! After `color-picker` `v2.0.0`, I rewrote everything, which may have caused this bug to reappear. It should, however, be fixed in `v2.0.7`.
