### ISSUE TITLE
color-picker doesn't show Stylus variable colors.

### ISSUE THREAD

**Issue by JamenMarz** [thomaslindstrom/color-picker#118]
It doesn't appear that Stylus variables are supported yet.

Then triggering the color-picker menu while a Stylus variable was selected, it just presents you with a new color selection instead of being able to view the color.

**Comment by JamenMarz** [comment]
Turns out it was an extension mishap.  One of the common Stylus extensions wasn't in the array, which happened to be the one I was using.

**Comment by thomaslindstrom** [comment]
Smooth, thanks! I didn't know about that extension. I'll pull this ASAP.

**Comment by thomaslindstrom** [comment]
Hi, this is added in `v2.0.7`.
