### ISSUE TITLE
Wrongly allows to convert partly-transparent colors to hexadecimal

### ISSUE THREAD

**Issue by miclf** [thomaslindstrom/color-picker#127]
Let’s say we load the color picker from the following value:

```
rgba(224, 131, 131, 0.86)
```

If we ask it to convert this color to hexadecimal, it will end writing this:

```
rgba(#e08383, 0.86)
```

As far as I know, this syntax does not exist in CSS, thus making it invalid.

I suggest that the color picker prevents people from being able to choose hexadecimal conversion when working with a color that does not have 100% opacity.

**Comment by thomaslindstrom** [comment]
This is valid when working with `Sass`, hence its inclusion.

**Comment by miclf** [comment]
Thanks for the feedback. Since it’s valid in some circumstances only, what about displaying a notice when this kind of conversion happens? People would then be warned in an clear way that it’s only valid in Sass syntax. Then it would be up to them to proceed or to cancel the conversion.

**Comment by thomaslindstrom** [comment]
Hmm... Instead of doing that, I might only convert colors into Sass `HEXA` format if the current file format agrees.

**Comment by ncammarata** [comment]
Running into this issue +1

**Comment by Mottie** [comment]
Why not check the file extension? If it's SASS, then use `rgba(#000000, .2)`, if not use the standard CSS format.

**Comment by thomaslindstrom** [comment]
That's [the idea](https://github.com/thomaslindstrom/color-picker/issues/127#issuecomment-121069481).

**Comment by Mottie** [comment]
<img title=":_ derp :" src="https://cloud.githubusercontent.com/assets/136959/13559387/49e2ecce-e3d9-11e5-8a16-73cbfdb7230e.gif"> I should learn to read better!
