### ISSUE TITLE
Shortcut ... !?

### ISSUE THREAD

**Issue by joopvos** [thomaslindstrom/color-picker#132]
Very useful plugin ... thanks. A keyboard shortcut would be very handy ... :)

Ah ... CMD + Shift + C ... :)

**Comment by thomaslindstrom** [comment]
Thanks! Yes. You could also customize the key binding to have another trigger key.

> Open `Atom Settings`, go to `Packages` in the left hand sidebar, and press `Settings` on `color-picker` to open the list of settings available for the Color Picker.
> **Trigger key**: Decide what trigger key should open the Color Picker. `CMD-SHIFT-{TRIGGER_KEY}` and `CTRL-ALT-{TRIGGER_KEY}`. Requires a restart.
