### ISSUE TITLE
Empty ColorPicker div at bottom of window

### ISSUE THREAD

**Issue by morassman** [thomaslindstrom/color-picker#143]
When Color Picker is installed along with [Atom Commander](https://atom.io/packages/atom-commander) an empty space sometimes appears at the bottom of the window. Upon inspection one can see that it's a div with class ColorPicker.

![screenshot](https://cloud.githubusercontent.com/assets/13697130/10616172/0ff7eadc-7764-11e5-816a-e1b773077bc5.png)

This may be a bug on Atom Commander's side or maybe it's a combination of issues between the two packages.

To reproduce, install both packages. Open Atom Commander by pressing F9. Each time its panel gets focus, either by clicking on it or pressing F9, the empty space appears.

I've noticed that if the color picker is shown at least once, the panel stops appearing. Further debugging showed that if the ColorPicker div has an initial top position of 0 it never appears.

**Comment by thomaslindstrom** [comment]
Please update `color-picker` to `v2.1.1` and **restart Atom**. This should be fixed now!

**Comment by morassman** [comment]
Thanks! It doesn't appear anymore.

**Comment by thomaslindstrom** [comment]
Great!
