### ISSUE TITLE
Depreciated call: This is now a view method. Call TextEditorElement::onDidChangeScrollTop instead.

### ISSUE THREAD

**Issue by Huaraz2** [thomaslindstrom/color-picker#145]
I have the latest stable release of atom and the latest version of color-picker, I have tried to see where this problem is but can't find it.  Below is a picture of what comes up
![depreciated call for color-picker](https://cloud.githubusercontent.com/assets/8998661/10882401/5317b2cc-8162-11e5-8964-8f2ef970632b.png)

**Comment by thomaslindstrom** [comment]
Yes, `color-picker` is calling a lot of deprecated functions. I'll look into this.

**Comment by thomaslindstrom** [comment]
This should be fixed now!
