### ISSUE TITLE
Color selector stuck to mouse cursor

### ISSUE THREAD

**Issue by Stsosz** [thomaslindstrom/color-picker#146]
As soon as i click anywhere on the menu my mouse cursor is stuck to the element that I clicked. I cannot click to select a color, and nothing will get the cursor unstuck except for hitting ESC or a key. 

I am using OS X El Capitan 10.11.1 on a MacBook Air 6.2. I have no peripherals plugged in. I have restarted multiple times and tried on many different color formats. 

https://vid.me/QZY2

Turned on mouse clicks and opened a keyboard viewer so you can see what i am doing. 

Edit: Sorry about the video... Apparently Github doesn't like Quicktime movies.

**Comment by thomaslindstrom** [comment]
You seem to have uploaded the movie icon, not the video. Could you try again?

**Comment by Stsosz** [comment]
The video was uploaded several days ago... I'm not sure of you get an alert on edits so here ya go...

**Comment by thomaslindstrom** [comment]
Alright, so basically the `mouseup` event handler isn't firing. What version of Atom are you on, and what version of `color-picker`?

**Comment by Stsosz** [comment]
I am using atom 1.1.0, and color-picker 2.0.13

**Comment by thomaslindstrom** [comment]
Hi, @Stsosz. Some users are reporting this issue is fixed. How's it for you?
