### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Jojokats** [thomaslindstrom/color-picker#148]
Hi,
Can't seem to switch from rgb to hex or any other ones, seems to be stuck on rgb. Also by clicking the color bar and transparent bar, they automatically both move up and down as I move the mouse to pick a color. 
I'm on a OS X 10.10.5
Can you fix this.
Thanks,
Joanna

**Comment by thomaslindstrom** [comment]
Hi. Are you able to record a video of the problem using QuickTime Screen Record?

**Comment by Jojokats** [comment]
Hi, yes I will send recordingthanksJoannaDate: Fri, 13 Nov 2015 01:46:37 -0800

**Comment by Jojokats** [comment]
Hi, I tried sending it via email, I don't know if you got it. I tried via Github but it won't work.
Please let me know.
Thanks,
Joanna

**Comment by thomaslindstrom** [comment]
I didn't get it, no. Could you try uploading it to a cloud service like cl.ly or mega.nz?

**Comment by Jojokats** [comment]
I uploaded it to https://my.cl.ly/ but don't know how to proceed. Please advise

**Comment by Stsosz** [comment]
That's the same problem as the one i am having in #147...

**Comment by Jojokats** [comment]
Hi, Have you had a chance to look into the link I sent you on cl.ly?Date: Fri, 13 Nov 2015 06:56:21 -0800

**Comment by thomaslindstrom** [comment]
Yeah, and as suspected by @Stsosz, it cloud be the same problem. I haven't had a chance to look into it just yet, but I might be able to squeeze in some time later today.

**Comment by leonewang** [comment]
I think i met the same question, is there any solution？

![color-picker-error](https://cloud.githubusercontent.com/assets/7222573/11413554/1cf2b932-9425-11e5-969d-91609c354ade.gif)

**Comment by thomaslindstrom** [comment]
Do you have any other packages installed?

**Comment by Jojokats** [comment]
Yes I do but now when I click on a color I get this error:
Uncaught SyntaxError: Failed to execute 'addColorStop' on 'CanvasGradient'....
Error: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('rgba(-Infinity, NaN, Infinity, 1)') could not be parsed as a color.
  at Error (native)
  at Object._this.canvas.render.....

**Comment by leonewang** [comment]
Update +1, update and restarted Atom that it will work.

**Comment by thomaslindstrom** [comment]
That's great! Not sure what I did that might have fixed it, though. Let me know if any other issues surface.
