### ISSUE TITLE
Extremely slow start-up

### ISSUE THREAD

**Issue by intellix** [thomaslindstrom/color-picker#152]
I'm not sure if this is happening all the time but as I'm debugging slow-startup of Atom I'm going through each pakage.

Color picker adds 414ms for me: https://www.dropbox.com/s/e6x2u530gdt7r2h/Screenshot%202015-12-03%2012.39.03.png?dl=0

Anyone else getting this?

**Comment by thomaslindstrom** [comment]
OS and specs?
<img width="675" alt="screen shot 2015-12-03 at 12 45 10" src="https://cloud.githubusercontent.com/assets/2833514/11559954/1ce35256-99bd-11e5-9b64-ad9228de048a.png">

**Comment by intellix** [comment]
Ahah, this time it was 63ms. OSX - MBP 13". I think the startup time varies quite drastically, maybe they're affected by other packages? Apologies for not double checking.

**Comment by DanielGGordon** [comment]
I have the same thing 
![image](https://cloud.githubusercontent.com/assets/11824880/12427998/dd9e80b0-bea7-11e5-9a7d-9cf8d510c1b6.png)
