### ISSUE TITLE
Color Highlighting for each value.

### ISSUE THREAD

**Issue by Jeremboo** [thomaslindstrom/color-picker#160]
Hi !

I just trying your package and it's for me the better color-picker never seen on text editor ! Nice work !

Just one thing, Do you think having a highlighting color on each code can be a good idea ?

Example with [atom-color-highlight-gmod (who does not work)](https://atom.io/packages/atom-color-highlight-gmod) : 
![](https://camo.githubusercontent.com/23197a747bd89aea774e0688ca932c6c0f9642cb/687474703a2f2f692e696d6775722e636f6d2f58497951684b482e706e67)

or this sublime text plugin [ColorHighlighter](https://github.com/Monnoroch/ColorHighlighter) :
![](https://camo.githubusercontent.com/e13f5346a650e7e3fc2269fd4de3904d78c8fd1e/687474703a2f2f692e696d6775722e636f6d2f55506d456b30392e706e67)

**Comment by thomaslindstrom** [comment]
You should probably use https://github.com/abe33/atom-pigments.

**Comment by Jeremboo** [comment]
Great thx you !
