### ISSUE TITLE
Uncaught SyntaxError: Failed to execute 'addColorStop' on 'CanvasGradient'

### ISSUE THREAD

**Issue by Sarath-VS** [thomaslindstrom/color-picker#169]
The package showing the following error

Uncaught SyntaxError: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('rgba(NaN,NaN,NaN,1)') could not be parsed as a color.

**Comment by thomaslindstrom** [comment]
Please update the `color-picker` and restart Atom.

**Comment by Sarath-VS** [comment]
i did that. Now working fine. Thanks
