### ISSUE TITLE
Hex in RGBA?

### ISSUE THREAD

**Issue by steelbrain** [thomaslindstrom/color-picker#170]
@thomaslindstrom I'm confused because I searched for this on google and couldn't find it to be a part of any spec. Can you please tell us the spec that allows this?

I'm talking about this behavior: https://v.usetapes.com/Nu25L75YLh

cc @ncammarata

**Comment by thomaslindstrom** [comment]
It's supported in [Sass](http://sass-lang.com/). This issue was brought up here https://github.com/thomaslindstrom/color-picker/issues/127, and the solution will eventually be deciding whether or not to use “`HEXA`” based on the current file extension. 

Please follow up on the existing issue.
