### ISSUE TITLE
Picker opens in wrong position where there is a left sidebar

### ISSUE THREAD

**Issue by lorenzos** [thomaslindstrom/color-picker#172]
![byzanz-record](https://cloud.githubusercontent.com/assets/245615/12972977/c85129ce-d0a9-11e5-9cc6-57f481fc90e2.gif)

Last version of Atom, all packages just updated:
```
packages: [
  "color-picker"
  "emmet"
  "file-icons"
  "highlight-selected"
  "linter"
  "linter-jshint"
  "local-history"
  "minimap"
  "minimap-bookmarks"
  "minimap-codeglance"
  "minimap-find-and-replace"
  "minimap-git-diff"
  "minimap-linter"
  "minimap-selection"
  "package-sync"
  "pigments"
  "term3"
]
```

**Comment by thomaslindstrom** [comment]
What OS are you on?

**Comment by lorenzos** [comment]
Ubuntu. Can't remember the exact version atm, I think 15.04

**Comment by thomaslindstrom** [comment]
A fix for this was merged in https://github.com/atom/atom/pull/11274, which means a fix for this should be out relatively soon.

**Comment by lorenzos** [comment]
To me, still broken with Atom 1.8.0 and `color-picker` 2.2.2. Shouldn't be fixed?
