### ISSUE TITLE
Support for rgba

### ISSUE THREAD

**Issue by newelement** [thomaslindstrom/color-picker#174]
Possible to support rbga ?

**Comment by thomaslindstrom** [comment]
It is already supported.

> Currently reads HEX, HEXa, RGB, RGBa, HSL, HSLa, HSV, HSVa, VEC3 and VEC4 colors – and is able to convert between the formats.

![Color Picker in action](https://github.com/thomaslindstrom/color-picker/raw/master/preview.gif)

**Comment by newelement** [comment]
When I try to use rgba this is the result.

![feb 13 2016 11 11](https://cloud.githubusercontent.com/assets/188085/13028635/994a6bfa-d242-11e5-979a-b3df2ba895d1.gif)

**Comment by thomaslindstrom** [comment]
It will need to be prefixed `rgb` or `rgba` for it to work. I'm not aware of any spec where `(000,000,000,0.3)` is a valid CSS color.

**Comment by newelement** [comment]
It is the gif recorder did not get that font color for some reason

**Comment by newelement** [comment]
I need to find a better gif recorder...

**Comment by newelement** [comment]
Ok let me try this again :-)

![color](https://cloud.githubusercontent.com/assets/188085/13028677/ca6dca96-d243-11e5-98b3-8550dc38a63a.gif)

**Comment by thomaslindstrom** [comment]
So it is prefixed with `rgb` and `rgba`? If that is the case, I assume the `rgb` matcher doesn't match `000`. If you change it to `0`, it should work. I could support triplets, though, but I'm not sure on what grounds. I'm pretty sure the recommended format is `rgb(0, 10, 200)`.

**Comment by newelement** [comment]
rgba

**Comment by newelement** [comment]
Did the last video clear it up ok? Sorry for the shotty first video.

**Comment by thomaslindstrom** [comment]
Yeah:

> I assume the rgb matcher doesn't match `000`. If you change it to `0`, it should work. I could support triplets, though, but I'm not sure on what grounds. I'm pretty sure the recommended format is `rgb(0, 0, 0, 0.3)`.

**Comment by newelement** [comment]
rgba(0,0,0,0.3); did not work

**Comment by thomaslindstrom** [comment]
That's weird. If you right-click that color value and select `Color Picker`, does it work?

<img width="280" alt="screen shot 2016-02-13 at 17 32 53" src="https://cloud.githubusercontent.com/assets/2833514/13028728/eadaaf68-d277-11e5-86f1-141b2ebe216c.png">

**Comment by newelement** [comment]
No it does not

**Comment by thomaslindstrom** [comment]
Alright, could you restart Atom and post a screencap of that?

**Comment by newelement** [comment]
Well it does but the color is incorrect

**Comment by newelement** [comment]
Screencap coming.

**Comment by newelement** [comment]
OK restarting atom fixed the right-click option

**Comment by newelement** [comment]
![color](https://cloud.githubusercontent.com/assets/188085/13028737/1db33860-d246-11e5-8365-dc9809e02a1d.gif)

**Comment by thomaslindstrom** [comment]
But does the sidebar option work?

**Comment by newelement** [comment]
No it does not

**Comment by thomaslindstrom** [comment]
Then it might be an issue with that package. What package is it? Please open an issue on that package repository and reference this issue in its description.

**Comment by newelement** [comment]
OK thanks!
