### ISSUE TITLE
Adds lots of time to startup.

### ISSUE THREAD

**Issue by mythmon** [thomaslindstrom/color-picker#18]
The settings view says that this package adds 581ms to startup time. This is the biggest impact of any package that I have installed. It would be awesome if some optimization to start up time could happen :smile_cat: 

![shot_31391](https://cloud.githubusercontent.com/assets/305049/2939647/c4c2506c-d952-11e3-83c7-7fbbc603cbac.png)

**Comment by fiws** [comment]
Can confirm. Its still like this.
![screenshot from 2015-01-16 13 39 35](https://cloud.githubusercontent.com/assets/3409958/5776269/3193d714-9d85-11e4-9645-81a9b72291f2.png)

**Comment by thomaslindstrom** [comment]
I've made some changes and performance improvements in `1.4.3`, and I keep getting a steady `12ms` activation time. The only exception is the first time Atom fires, and the activation time peaks at around `250ms`. I'm thinking this has something to do with something being cached. 

I'll continue to improve the activation time sporadically.

**Comment by fiws** [comment]
:+1 Seems a lot better now. Getting about 10ms load time after the first load.

**Comment by thomaslindstrom** [comment]
Performance and startup time is vastly improved in the upcoming `v2.0.0`.
