### ISSUE TITLE
I can't install the package, help!

### ISSUE THREAD

**Issue by Lawsssss** [thomaslindstrom/color-picker#181]
Below is what i received :

Installing “color-picker@2.1.1” failed.Show output…
Compiler tools not found
Packages that depend on modules that contain C/C++ code will fail to install.
Read here for instructions on installing Python and Visual Studio.
Run apm install --check after installing to test compiling a native module

Who can tell me what has happen ?

**Comment by thomaslindstrom** [comment]
That's weird, because `color-picker` [has no dependencies](https://github.com/thomaslindstrom/color-picker/blob/master/package.json).
