### ISSUE TITLE
Spaces after commas in RGB HSL etc.

### ISSUE THREAD

**Issue by smlombardi** [thomaslindstrom/color-picker#183]
Can you please add a config option to add spaces after commas in color formats which use them?  Some lint styles prefer spaces after commas.

**Comment by thomaslindstrom** [comment]
There is, already! 

```
**Abbreviate Color Values**: If possible, abbreviate color values, like for example “0.3” to “.3”, “#ffffff” to “#fff” and “rgb(0, 0, 0)” to “rgb(0,0,0)”.
```

If this is not what you wanted, please let me know.

**Comment by smlombardi** [comment]
I see.  I would not consider the comma space/no space as an "abbreviation".  I would consider the first two abbreviations but the last a code style.

The default settings for stylelint and scss-lint expect the other abbreviations (e.g. ".3") but not the lack of spaces. So, If I un-tick "use abbreviations" the other will be flagged as errors.
