### ISSUE TITLE
No Code-Format providers registered for scope: 

### ISSUE THREAD

**Issue by vimniky** [thomaslindstrom/color-picker#185]
What's this ? can any body help?
<img width="453" alt="screen shot 2016-05-10 at 1 33 25 am" src="https://cloud.githubusercontent.com/assets/11426875/15121910/3a2483c6-164f-11e6-8d7c-086983bc3c3f.png">

**Comment by thomaslindstrom** [comment]
I don't think this issue is related to `color-picker`. Please let me know if it is. Closing this issue for now.

**Comment by fabioanselmo** [comment]
@vimniky if you have `nuclide` installed, that module is causing the problem. Try this: `apm uninstall nuclide` and restart Atom.

**Comment by gwing33** [comment]
There is an unrelated ticket open about this error (still): https://github.com/facebook/nuclide/issues/386

Some might not want to uninstall `nuclide`, so you can disabled the Keybindings in the color-picker package and rebind them to a new key.

```cson
'atom-text-editor':
  'cmd-shift-e': 'color-picker:open'
```
