### ISSUE TITLE
Publish new version with 'Fix compatibilty with Tool Bar package'

### ISSUE THREAD

**Issue by brumm** [thomaslindstrom/color-picker#188]
Hey @thomaslindstrom, it would be fantastic if you could publish a new version that includes https://github.com/thomaslindstrom/color-picker/commit/335fce538b09064eea93483eefc14e74906fdb4a.
We ran into the same problems as https://github.com/suda/tool-bar/issues/130 over at  https://github.com/atom/atom/pull/11790 and would benefit from that fix as well.

See https://github.com/atom/atom/pull/11790#issuecomment-230154158 and following comments for some context.

**Comment by thomaslindstrom** [comment]
Hi, sorry, I thought I'd done this. It's out in `2.2.0`.

**Comment by brumm** [comment]
Awesome, thank you!
