### ISSUE TITLE
[usage question] [support needed] Converting HSL to rgb

### ISSUE THREAD

**Issue by hellboy81** [thomaslindstrom/color-picker#193]
How can I convert this text with `hsl` values to `rgb`:

````js
hsl(0, 0%, 100%)
hsl(350, 80%, 41%)
````

**Comment by hellboy81** [comment]
Another question: is there possible to highlight this values editor if file has `JSON` format

**Comment by thomaslindstrom** [comment]
Just open the `color-picker` on the colors. If you'd like to convert them, you can press the buttons in the bottom of the UI. 

![color-picker](https://github.com/thomaslindstrom/color-picker/raw/master/preview.gif)
