### ISSUE TITLE
Stylus color picker 

### ISSUE THREAD

**Issue by tomaszbakula** [thomaslindstrom/color-picker#197]
It's more like the new feature than the issue but the color picker doesn't work if we use Stylus. It works perfect for Less/Sass. I love it but with Stylus the only thing which I get is "No color found.".  Is there any way to provide support for Stylus?

**Comment by thomaslindstrom** [comment]
Could you provide a screenshot or some context of the color you're trying to look up? `color-picker` should have Stylus support, but it requires your variables to be prefixed with a `$`.

**Comment by tomaszbakula** [comment]
As you can see at the attached screenshot I have a file called "variables.styl" which contains `$primary-color` variable and it's imported in the "style.styl".
If these information are useful I'm using Atom 1.11.2 and  color-picker 2.2.2
![screenshot from 2016-11-01 22-43-47](https://cloud.githubusercontent.com/assets/21692310/19910481/133bf878-a085-11e6-8f57-7dd82d2ee0b1.png)

**Comment by thomaslindstrom** [comment]
Right. Are all variables in Stylus defined using a `=`? `color-picker` is looking for definitions preceded by a `:`.
