### ISSUE TITLE
The contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary.

### ISSUE THREAD

**Issue by att1cus** [thomaslindstrom/color-picker#204]
Version: 2.2.3
OS: Windows 10

The contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. Please, stop using shadowRoot and access the editor contents directly instead.

`atom-text-editor.Object.defineProperty.get - C:\Users\Niki\AppData\Local\atom\app-1.13.0\resources\app.asar\src\text-editor-element.js:68:18
Object.open - C:\Users\Niki\.atom\packages\color-picker\lib\ColorPicker-view.coffee:318:32
atom-text-editor.<anonymous> - C:\Users\Niki\.atom\packages\color-picker\lib\ColorPicker.coffee:36:29
CommandRegistry.handleCommandEvent - C:\Users\Niki\AppData\Local\atom\app-1.13.0\resources\app.asar\src\command-registry.js:259:29
<unknown> - C:\Users\Niki\AppData\Local\atom\app-1.13.0\resources\app.asar\src\command-registry.js:3:59
KeymapManager.dispatchCommandEvent - C:\Users\Niki\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:587:16`

**Comment by thomaslindstrom** [comment]
Hi, @att1cus. This should be fixed in `v2.2.5`.

**Comment by ta-riq** [comment]
IS i fixed , sir ? i have the same problem.. Though i dont know if it is prohibiting me from using any service.. 


hoping to fix this soon.
