### ISSUE TITLE
This is now a view method. Call TextEditorElement::pixelRectForScreenRange instead.

### ISSUE THREAD

**Issue by att1cus** [thomaslindstrom/color-picker#205]
Version: 2.2.3
OS: Windows 10

This is now a view method. Call TextEditorElement::pixelRectForScreenRange instead.

`TextEditor.pixelRectForScreenRange - C:\Users\Niki\AppData\Local\atom\app-1.13.0\resources\app.asar\src\text-editor.js:3559:12
Cursor.getPixelRect - C:\Users\Niki\AppData\Local\atom\app-1.13.0\resources\app.asar\src\cursor.js:675:26
Object.open - C:\Users\Niki\.atom\packages\color-picker\lib\ColorPicker-view.coffee:401:36
atom-text-editor.<anonymous> - C:\Users\Niki\.atom\packages\color-picker\lib\ColorPicker.coffee:36:29
CommandRegistry.handleCommandEvent - C:\Users\Niki\AppData\Local\atom\app-1.13.0\resources\app.asar\src\command-registry.js:259:29
<unknown> - C:\Users\Niki\AppData\Local\atom\app-1.13.0\resources\app.asar\src\command-registry.js:3:59`

**Comment by thomaslindstrom** [comment]
Hi, @att1cus. This should be fixed in `v2.2.4`.
