### ISSUE TITLE
The contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. Please, stop using shadowRoot and access the editor contents directly inste

### ISSUE THREAD

**Issue by ProhosMS** [thomaslindstrom/color-picker#208]
atom-text-editor.Object.defineProperty.get - C:\Users\god\AppData\Local\atom\app-1.13.0\resources\app.asar\src\text-editor-element.js:68:18
Object.open - C:\Users\god\.atom\packages\color-picker\lib\ColorPicker-view.coffee:319:32
atom-text-editor.<anonymous> - C:\Users\god\.atom\packages\color-picker\lib\ColorPicker.coffee:36:29
CommandRegistry.handleCommandEvent - C:\Users\god\AppData\Local\atom\app-1.13.0\resources\app.asar\src\command-registry.js:259:29
handleCommandEvent - C:\Users\god\AppData\Local\atom\app-1.13.0\resources\app.asar\src\command-registry.js:3:59
CommandRegistry.dispatch - C:\Users\god\AppData\Local\atom\app-1.13.0\resources\app.asar\src\command-registry.js:160:19

**Comment by thomaslindstrom** [comment]
Hi, @ProhosMS. This should be fixed in `v2.2.5`.
