### ISSUE TITLE
can we get  the color shown to the right or left of the color like webstorm?

### ISSUE THREAD

**Issue by joncodo** [thomaslindstrom/color-picker#210]
and auto open the color picker when you click the colored square on the left

![screen shot 2017-01-26 at 9 50 23 am](https://cloud.githubusercontent.com/assets/3011407/22333493/defbe77e-e3ac-11e6-947e-2c7ade3e3dd2.png)

Awesome work!

**Comment by thomaslindstrom** [comment]
Hi, @joncodo! You could probably use [pigments](https://github.com/abe33/atom-pigments) for that.
