### ISSUE TITLE
Feature Request: add hex code to color suggest menu

### ISSUE THREAD

**Issue by dhniels** [thomaslindstrom/color-picker#224]
I wonder if this is possible? it would be cool to be able to show a hex code to the right of the little color preview circle (see screenshot). maybe this is a feature for atom and not your color-picker plug in? I'm new to atom so perhaps I'm posting this in the wrong place.

![screen shot 2017-08-03 at 1 33 12 pm](https://user-images.githubusercontent.com/7034022/28940024-7c72816a-7850-11e7-8525-60e78e16b55d.png)

**Comment by thomaslindstrom** [comment]
Welcome to Atom! Good idea, but this might be a better fit for the `pigments` package. https://atom.io/packages/pigments

**Comment by dhniels** [comment]
ok! thanks for pointing me to the right place.
