### ISSUE TITLE
Hotkey(s) broken when using atom-ide-ui

### ISSUE THREAD

**Issue by matthew-ia** [thomaslindstrom/color-picker#231]
So atom-ide-ui has some new hotkeys stock Atom does not, such as Format Code (cmd-shift-c), which is the default for color-picker. However, even when I change the color-picker hotkey to any of the other hotkey options, it doesn't work (even after a restart of Atom). 

_Atom version: 1.22.1_
_macOS_

**Comment by octoquad** [comment]
Also affects Atom for Linux 1.21.1.

**Comment by Princeraul** [comment]
me to

**Comment by thomaslindstrom** [comment]
Hi! You can change the key binding within the Color Picker settings.
Go to `Settings` › `Color Picker Settings` › `Trigger key`.

Either that, or disable the `atom-ide-ui` Format Code shortcut through its settings.

**Comment by matthew-ia** [comment]
Folks who were experiencing this issue:

I _was_ rebinding via `Settings` › `Color Picker Settings` › `Trigger key`, but it was still not working. **I neglected to check if _other_ packages had additional hotkeys that were conflicting** with `color-picker`'s alternate options. 

If you want to override `atom-ide-ui` go to `Settings` › `Keybindings` and at the top there's a link to open `your keymap file`. Then append this below the comments in `keymap.cson`:

```
'.platform-darwin atom-workspace atom-text-editor:not(.mini)':
  'shift-cmd-C': 'unset!'
  '<your-new-hotkey>': 'code-format:format-code'
```
