### ISSUE TITLE
Cannot open color picker

### ISSUE THREAD

**Issue by rugk** [thomaslindstrom/color-picker#235]
After extensions updates or so, I cannot open the color picker. It just does not show up.

**Comment by rugk** [comment]
Closing, as it seems to be an Atom issue.

**Comment by HugoMcPhee** [comment]
manually adding the keybinding to 'keymap.cson' fixed the issue for me

```
'atom-text-editor':
  'ctrl-alt-c': 'color-picker:open'
```

**Comment by chicken-suop** [comment]
MacOS equiv:
```
'atom-text-editor':
  'shift-cmd-C': 'color-picker:open'
```
