### ISSUE TITLE
Picker placed over cursor position when position at bottom of viewport

### ISSUE THREAD

**Issue by ilkka** [thomaslindstrom/color-picker#26]
This is not a huge problem, but if the cursor position is low enough, the picker is placed such that it hides the position, sorta snapped to the bottom of the viewport. It'd be nice if the picker would be e.g. offset horizontally such that the color value in the source would always be visible.

**Comment by thomaslindstrom** [comment]
A fix for this is included in the upcoming `v2.0.0`.
