### ISSUE TITLE
Some odd behaviour doesn't really let me pick anything...

### ISSUE THREAD

**Issue by lexbi** [thomaslindstrom/color-picker#32]
![color-picker](https://cloud.githubusercontent.com/assets/2337910/4017612/21f02206-2a42-11e4-8736-e7c84e17915e.gif)

So you're aware, I am on Yosemite Beta (2).
Latest Atom & latest color-picker.

Any ideas?

**Comment by thomaslindstrom** [comment]
Hi, sorry for the late reply. Have any of you experienced this issue as of late?

**Comment by tehRash** [comment]
It happened to me on Atom 0.174.0 today, but updating to the latest version of color picker seems to have fixed it, for now at least.

**Comment by thomaslindstrom** [comment]
This should be fixed in the upcoming `v2.0.0`.
