### ISSUE TITLE
[request] Stylus Variable Support

### ISSUE THREAD

**Issue by markmsmith** [thomaslindstrom/color-picker#4]
Can the upcoming Saas/Less variable support also handle Stylus variables?
What about the built-in functions like lighten(color, amount)? :D

**Comment by thomaslindstrom** [comment]
Hello, one year later! If preceded by `$`, Stylus variable support will land in the upcoming `v2.0.3`.

**Comment by markmsmith** [comment]
Awesome, thanks!
