### ISSUE TITLE
color-picker is taking too long to activate

### ISSUE THREAD

**Issue by Gespinha** [thomaslindstrom/color-picker#42]
Hi there,

I've noticed that ver since I've installed color-picker, Atom is slightly slower on load. While investigating the Timecop logs, I noticed that color-picker is taking a lot to activate (45-60ms).

This should definitely be optimised in order to stop influencing the speed of Atom.

Anything you can do regarding this?

![atom](https://cloud.githubusercontent.com/assets/4227944/4725308/5b939782-5958-11e4-8de0-3b098f8c582e.png)

Thanks in advance!

**Comment by thomaslindstrom** [comment]
Performance and startup time is vastly improved in the upcoming `v2.0.0`.
