### ISSUE TITLE
atom.workspaceView is deprecated.

### ISSUE THREAD

**Issue by fiws** [thomaslindstrom/color-picker#47]
Deprecation cop has a problem with you code. 

atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/usr/share/atom/resources/app/src/atom.js:55:11)
Object.activate (/home/fiws/dotfiles/atom.symlink/packages/color-picker/lib/ColorPicker.coffee:18:21)
```

Same warning for these lines:
```
/color-picker/lib/ColorPicker-view.coffee:39:18
/color-picker/lib/ColorPicker-saturationSelector.coffee:6:19
/color-picker/lib/ColorPicker-saturationSelector.coffee:7:26
/color-picker/lib/ColorPicker-alphaSelector.coffee:6:19
/color-picker/lib/ColorPicker-alphaSelector.coffee:7:26
/color-picker/lib/ColorPicker-hueSelector.coffee:7:19
/color-picker/lib/ColorPicker-hueSelector.coffee:8:26
/color-picker/lib/ColorPicker-view.coffee:154:17

**Comment by Koltharius** [comment]
Sane error

color-picker (9 deprecations)
atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use atom.views.getView(atom.workspace), which returns an HTMLElement.
Called 1 timeCreate Issue on color-picker repo

Atom.Object.defineProperty.get - /usr/share/atom/resources/app/src/atom.js:55:11
Object.activate - /home/david/.atom/packages/color-picker/lib/ColorPicker.coffee:18:21
Atom.Object.defineProperty.get - /usr/share/atom/resources/app/src/atom.js:55:11
ColorPickerView.initialize - /home/david/.atom/packages/color-picker/lib/ColorPicker-view.coffee:39:18
Atom.Object.defineProperty.get - /usr/share/atom/resources/app/src/atom.js:55:11
Object. - /home/david/.atom/packages/color-picker/lib/ColorPicker-saturationSelector.coffee:6:19
Atom.Object.defineProperty.get - /usr/share/atom/resources/app/src/atom.js:55:11
Object. - /home/david/.atom/packages/color-picker/lib/ColorPicker-saturationSelector.coffee:7:26
Atom.Object.defineProperty.get - /usr/share/atom/resources/app/src/atom.js:55:11
Object. - /home/david/.atom/packages/color-picker/lib/ColorPicker-alphaSelector.coffee:6:19
Atom.Object.defineProperty.get - /usr/share/atom/resources/app/src/atom.js:55:11
Object. - /home/david/.atom/packages/color-picker/lib/ColorPicker-alphaSelector.coffee:7:26
Atom.Object.defineProperty.get - /usr/share/atom/resources/app/src/atom.js:55:11
Object. - /home/david/.atom/packages/color-picker/lib/ColorPicker-hueSelector.coffee:7:19
Atom.Object.defineProperty.get - /usr/share/atom/resources/app/src/atom.js:55:11
Object. - /home/david/.atom/packages/color-picker/lib/ColorPicker-hueSelector.coffee:8:26
Atom.Object.defineProperty.get - /usr/share/atom/resources/app/src/atom.js:55:11
ColorPickerView.bind - /home/david/.atom/packages/color-picker/lib/ColorPicker-view.coffee:154:17
