### ISSUE TITLE
Cannot read property 'getView' of undefined

### ISSUE THREAD

**Issue by LM450N** [thomaslindstrom/color-picker#54]
Hello,

I updated my `color-picker` module and now it doesn't work anymore.
I restarted Atom 3 times and each time the package was not activated.

Do you have any idea ?

![color_picker_not_initialized](https://cloud.githubusercontent.com/assets/2325091/5825803/6e263502-a0ee-11e4-8b7e-4299e03bfe0a.png)

**Comment by thomaslindstrom** [comment]
Hi, what version of Atom are you using?

**Comment by LM450N** [comment]
Ok, I'm sorry.

I updated my Atom and my favorite module works like a charm ! =)

Thank you !

**Comment by thomaslindstrom** [comment]
Oh, great. Thanks for the kind words!
