### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by AlexUlrich** [thomaslindstrom/color-picker#57]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (c:\Users\alexu_000\AppData\Local\atom\app-0.176.0\resources\app\src\atom.js:53:11)
Object.activate (c:\Users\alexu_000\.atom\packages\color-picker\lib\ColorPicker.coffee:19:21)
```

**Comment by thomaslindstrom** [comment]
Hi! I'm not using `atom.workspaceView` anymore. What version are you on?

**Comment by AlexUlrich** [comment]
Hi. I just opened Atom again (v 0.176.0) the version of color picker is 1.4.4. It looks like I don't have this issue anymore, it must have been an issue with upgrading to the latest atom. My apologies. I will close this issue.
