### ISSUE TITLE
Strange pane appear occupying half of the screen

### ISSUE THREAD

**Issue by loque** [thomaslindstrom/color-picker#70]
When the plugin is enabled, there is a blank pane occupying half of the screen.I'm using version 1.5.0 in windows.
![atom-color-picker](https://cloud.githubusercontent.com/assets/623893/6790130/4da04fe0-d184-11e4-9355-261c9b6d2974.jpg)

**Comment by Ephphatha** [comment]
This happened for me on Win7 using Atom 0.155 and 0.174 (I think, the latest available using `cup Atom` as of today). Opening the color picker via the context menu would make it appear in the pane and not in a popup.

Upgrading to Atom 0.188 restored the look and feel, so when I opened the color picker it would appear in a popup as expected however the context menu entry is lost.

**Comment by loque** [comment]
Oh didn't noticed that there was a new version of atom. I will upgrade and inform here if that resolves the issue.

**Comment by loque** [comment]
Thanks, it's working now. I'm using Atom 0.189

**Comment by thomaslindstrom** [comment]
Thanks for letting me know. Please upgrade Atom to the newest version and try again.
