### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by SolusSoftworks** [thomaslindstrom/color-picker#72]
I feel this tool could be greatly improved by having different tabs for HSL, RGB and Hex. This would allow for quick switching between definition types as well as allow for the option to use RGB sliders or Hex sliders. It would also be nice to be able to use the keyboard to move the sliders.

**Comment by dubert** [comment]
See https://github.com/thomaslindstrom/color-picker/issues/3

**Comment by thomaslindstrom** [comment]
This will be included in the upcoming `v2.0.0`.
