### ISSUE TITLE
Object.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by GutierrezDev** [thomaslindstrom/color-picker#82]
Requiring `View` from `atom` is no longer supported.
Please require `atom-space-pen-views` instead:
  `{View} = require 'atom-space-pen-views'`
Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies.
```
Object.Object.defineProperty.get (C:\Users\rgutierrez\AppData\Local\atom\app-0.190.0\resources\app\exports\atom.js:62:11)
Object.<anonymous> (C:\Users\rgutierrez\.atom\packages\color-picker\lib\ColorPicker-view.coffee:5:5)
```

**Comment by thomaslindstrom** [comment]
Hi, please update `Atom` and `color-picker` and try again.
