### ISSUE TITLE
Getting deprecated calls – see #6278

### ISSUE THREAD

**Issue by clauseggers** [thomaslindstrom/color-picker#83]
Getting deprecated calls from color-picker, please see:
atom/atom#6278

**Comment by thomaslindstrom** [comment]
Hi, please update `Atom` and `color-picker` to the newest versions and try again.

**Comment by clauseggers** [comment]
I can see you haven’t yourself tried to isolate this problem. If you turn off all community packages except color-picker you get a deprecation call for atom-core:

atom core (1 deprecation)
ContextMenuManager::add has changed to take a single object as its argument. Please see https://atom.io/docs/api/latest/ContextMenuManager for more info.
Called 1 time
ContextMenuManager.add - /Applications/Atom.app/Contents/Resources/app/src/context-menu-manager.js:59:18
Package.activateResources - /Applications/Atom.app/Contents/Resources/app/src/package.js:296:61

This is caused by color-picker, not atom-core (hence the same situation as #6278 which I linked to.)

**Comment by thomaslindstrom** [comment]
I'm pretty sure I'm running the newest versions of both, and I see no deprecation warnings. What versions of both `Atom` and `color-picker` are you on?

**Comment by clauseggers** [comment]
I’m on Atom 0.192 and color-picker 1.6.0

**Comment by thomaslindstrom** [comment]
It was the `cson` menu file that was acting up, hence why `atom-core` was reporting the issue.

**Comment by clauseggers** [comment]
Cool – thanks for fixing this!
