### ISSUE TITLE
Unusable pane at bottom of the Window

### ISSUE THREAD

**Issue by curtismitchell** [thomaslindstrom/color-picker#84]
The latest version of Color Picker added a pane below the status bar.  It has a partial color picker.  The pane is unusable, and not removable without disabling Color Picker.

![image](https://cloud.githubusercontent.com/assets/20866/7189271/d915b680-e44b-11e4-864a-99ea6a452c89.png)

**Comment by thomaslindstrom** [comment]
Please try updating `Atom` and `color-picker`, then try again.

**Comment by thomaslindstrom** [comment]
This should be fixed in the upcoming `v2.0.0`.
