### ISSUE TITLE
[request] Change key bindings

### ISSUE THREAD

**Issue by krypsin** [thomaslindstrom/color-picker#88]
Maybe worth adding in custom keymap?

Would like to have something similar to what it is on Brackets
CTRL + E or something

**Comment by thomaslindstrom** [comment]
`CTRL + E` is taken, sadly. Would `CTRL + ALT + E` be better?

**Comment by thomaslindstrom** [comment]
Custom trigger keys is included as a setting in `color-picker` `v2.0.0`.
