### ISSUE TITLE
recognise vec3() and vec4() like rgb() and rgba()

### ISSUE THREAD

**Issue by blackjack75** [thomaslindstrom/color-picker#89]
Could be nice when fiddling with GLSL (shaders) to be able to pick a rgba color for vec4().

**Comment by thomaslindstrom** [comment]
Like `vec3(1.0f, 0.0f, 0.5f)` and `vec4(0.5, 1.0, 0.7, 0.4)`?

**Comment by blackjack75** [comment]
Yes, absolutely this.

**Comment by thomaslindstrom** [comment]
This will be included in the upcoming `v2.0.0`.
