### ISSUE TITLE
[2.0.0] Frequent Uncaught TypeError: Cannot read property 'getColorAtPosition' of null on startup or reload

### ISSUE THREAD

**Issue by Tribex** [thomaslindstrom/color-picker#94]
When starting Atom (or reloading the window,) Occasionally this error will display, and the respective parts of the color picker will be non-functional.

So far this happens only with the Hue and Saturation/Value selectors. (`Hue.coffee` and `Saturation.coffee`) 

Interestingly, if `Saturation.coffee` is the cause of an error, `Hue.coffee` is as well, and `Hue.coffee` errors far more frequently. I assume the same bug is present in `Alpha.coffee`, but it has yet to present itself.

```
TypeError: Cannot read property 'getColorAtPosition' of null
    at Object._this.control.setSelection (~/.atom/packages/color-picker/lib/extensions/Hue.coffee:144:50)
    at Object._this.control.refreshSelection (~/.atom/packages/color-picker/lib/extensions/Hue.coffee:156:29)
    at ~/.atom/packages/color-picker/lib/extensions/Hue.coffee:159:27
```

I assume this is related to the use of setTimeout to wait for the DOM. So far I cannot reproduce the error in safe mode, likely because the editor starts fast enough.

Atom Version: 0.201.0
color-picker Version: 2.0.0-pre
System: Ubuntu GNOME 15.04 x64

**Comment by thomaslindstrom** [comment]
Ohh, thanks! I was able to artificially recreate the error by using the `setTimeout` to delay the creation of the `Saturation` and `Hue` canvases. I pushed a fix for this now – I'd be glad if you tried it!

**Comment by Tribex** [comment]
Excellent, will test. :)

**Comment by Tribex** [comment]
Seems to be working fine now. Thanks!

**Comment by thomaslindstrom** [comment]
:+1:
