### ISSUE TITLE
Language agnostic color picker

### ISSUE THREAD

**Issue by waldirbertazzijr** [thomaslindstrom/color-picker#98]
I use alot of colors on my application inside javascript files because I work alot with charts. Is it possible to make color-picker language agnostic? That means it should work on every scope (e.g. JS or PHP).

**Comment by thomaslindstrom** [comment]
It already is! Or, should be, that is – is it not working for you?


    _____________________________

**Comment by waldirbertazzijr** [comment]
Sorry on that, my atom was outdated. I just updated it and it's working. Thanks!
